'use client';

import { useRef, useState } from "react";
import { Up } from "../../components";
import { Footer } from "../../components/Footer/Footer";
import { Header } from "../../components/Header/Header";
import { SideBar } from "../../components/SideBar/SideBar";
// import type { Metadata } from "next";
import styles from "./layout.module.css";
import cn from 'clsx';
import { Open_Sans } from 'next/font/google';
import Script from "next/script";

const inter = Open_Sans({ subsets: ['latin'] });



// export const metadata: Metadata = {
//   title: "My training project",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children, one, two
}: Readonly<{
  children: React.ReactNode,
  one: React.ReactNode,
  two: React.ReactNode
}>) {

  const [isSkipLink, setIsSkipLink] = useState<boolean>(false);
  const bodyRef = useRef<HTMLDivElement>(null);

  const skipContentAction = (key: KeyboardEvent) => {
    if (key.code == 'Space' || key.code == 'Enter') {
      key.preventDefault();
      bodyRef.current?.focus();
    }
    setIsSkipLink(false);
  };

  return (<html lang='en'>
    <head>
      <Script src="" strategy="beforeInteractive"/>
    </head>
    <body className={inter.className}>
      <div className={styles.wrapper}>
        <a
          tabIndex={1}
          onFocus={() => setIsSkipLink(true)}
          className={cn(styles.skipLink, {
            [styles.displayed]: isSkipLink
          })}
          onKeyDown={skipContentAction}
        >Go to contain</a>
        <Header className={styles.header} />
        <SideBar className={styles.sidebar} />
        <main className={styles.body} ref={bodyRef} tabIndex={0} role="main">
          {children}
          {one}
          {two}
        </main>
        <Footer className={styles.footer} />
        <Up />
      </div>
    </body>
  </html>
  );
}
