'use client';

import { Footer } from "../../components/Footer/Footer";
import { Header } from "../../components/Header/Header";
import { SideBar } from "../../components/SideBar/SideBar";
// import type { Metadata } from "next";
import styles from "./layout.module.css";



// export const metadata: Metadata = {
//   title: "My training project",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children, one, two
}: Readonly<{
  children: React.ReactNode,
  one: React.ReactNode,
  two: React.ReactNode
}>) {

  return (<html lang='en'>
    <body>
      <div className={styles.wrapper}>
        <Header className={styles.header}/>
        <SideBar className={styles.sidebar}/>
        <div className={styles.body}>
          {children}
          {one}
          {two}
        </div>
        <Footer className={styles.footer}/>
      </div>
    </body>
  </html>
  );
}
