'use client';

import { Button, Htag, Paragraph, Rating } from "../components/index";
// import type { Metadata } from "next";
import "./globals.css";
import Logo from '../public/vercel.svg';
import { useState } from "react";


// export const metadata: Metadata = {
//   title: "My training project",
//   description: "Generated by create next app",
// };

export default function RootLayout() {

  const [rating, setRating] = useState<number>(4)

  return (<>
    <Htag tag='h1'>Text</Htag>
    <Logo />
    <Button appearance="primary" arrow="down">Button</Button>
    <Paragraph size="l">Big</Paragraph>
    <Paragraph>Medium</Paragraph>
    <Paragraph size="s">Small</Paragraph>
    <Rating rating={rating} isEditable setRating={setRating}/>
  </>
  );
}
