'use client';

import { Button, Htag } from "@/components";
// import type { Metadata } from "next";
import "./globals.css";
import Logo from '../public/vercel.svg';


// export const metadata: Metadata = {
//   title: "My training project",
//   description: "Generated by create next app",
// };

export default function RootLayout() {
  return (<>
    <Htag tag='h1'>Text</Htag>
    <Logo />
    <Button appearance="primary" arrow="down">Button</Button>
  </>
  );
}
