import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Head, NextScript } from "next/document";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My training project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head />
      <body className={inter.className}><main>{children}</main><NextScript /></body>
    </html>
  );
}
